# Generated by Django 4.2.2 on 2023-06-30 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0002_remove_registermodel_repin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registermodel',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
