# Generated by Django 4.2.2 on 2023-06-30 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0003_alter_registermodel_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registermodel',
            name='phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='registermodel',
            name='pin',
            field=models.CharField(max_length=10),
        ),
    ]
