# Generated by Django 4.2.1 on 2023-07-02 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0004_alter_registermodel_phone_alter_registermodel_pin'),
    ]

    operations = [
        migrations.CreateModel(
            name='loginmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=30)),
                ('pin', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='registermodel',
            name='pin',
            field=models.IntegerField(),
        ),
    ]
