# Generated by Django 4.2.2 on 2023-07-11 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0008_addamount'),
    ]

    operations = [
        migrations.CreateModel(
            name='mini',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement', models.IntegerField(choices=[('withdraw', 'withdraw'), ('deposit', 'deposit')])),
            ],
        ),
    ]
