# Generated by Django 4.2.2 on 2023-07-11 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0011_adminmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminmodel',
            name='content',
            field=models.CharField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='adminmodel',
            name='topic',
            field=models.CharField(max_length=300),
        ),
    ]
